file_path: "/home/doyooni303/teaching/SK_Hynix/PBL_TAT_Set_Data Rev2(사외).xlsx"
indicies_columns: ['timekey_hr','oper_id']
categorical_columns: ["oper_group", "days", "shift", "x1"]
continuous_columns: ["x2", "x3", "x4", "x5", "x6", "x7", "x8", "x9", "x10", "x11", "x12", "x13", "x14", "x15", "x16", "x17", "x18", "x19", "x20", "x21"]
target_column: "y"
sheet_names: ["Data_Set1(사외)", "Data_Set2(사외)"]
additional_drop_columns: ["lot_cd", "oper_area"]
train_ratio: 0.8
val_ratio: 0.1
test_ratio: 0.1
normalize_continuous: false
# Categories unique values
categories: [277, 7, 3, 20]  # oper_group, days, shift, x1