# 기본 모델 설정
model_type: "lstm"  # rnn, lstm, gru, rnn_attention, lstm_attention, gru_attention, cnn1d
embedding_dim: 8
hidden_dim: 128
num_layers: 2
dropout: 0.1
bidirectional: true
padding_value: -999999.0

# RNN + Attention 설정
num_attention_heads: 8

# CNN1D 설정  
kernel_sizes: [3, 5, 7]
num_filters: 64
