# 훈련 하이퍼파라미터
num_epochs: 100
learning_rate: 0.001
patience: 20

# 옵티마이저 설정
optimizer: "adamw"
weight_decay: 0.01

# 스케줄러 설정
scheduler: "reduce_on_plateau"
scheduler_factor: 0.5
scheduler_patience: 10

# 저장 설정
save_dir: "250831_test"
exp_name: null  # null이면 자동 생성

# 로깅 설정
log_file: "training.log"